language: java
addons:
  sonarcloud:
    organization: "definelogic"
    token:
     secure: 3c53f35e5b66413b391db3e1ab8847547ec7789d
jdk:
  - oraclejdk9
script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
