language:java
sudo:false
addons:
  sonarcloud:
    organization:"definelogic"
  token:
    secure:3c53f35e5b66413b391db3e1ab8847547ec7789d
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco.jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
